### ISSUE TITLE
Investigate visualising tool

### ISSUE THREAD

**Issue by yasmine9** [NethermindEth/restaking-dashboard#1]
voyager.online uses re-charts
https://recharts.org/en-US/

Suggest a better tool if you know

**Comment by EdgarBarrantes** [comment]
I had used recharts in the past and I feel it lacks a bit in aesthetics, what do you think of [Charts.js](https://www.chartjs.org/)?

**Comment by yasmine9** [comment]
I’ve made some research about tools and here are my findings: 

One of the most recommended tools for data vizualization with React/ Next js are `D3.js` and `Chart.js`, D3.js offers more variety of graphs but it requires time to learn ( not intuitive to use). 
I’ve had a look at **Recharts**, it is a good one too but Chart.js seems to be more complete and better in term of performances:  Rechart.js is DOM heavy as it uses on SVG elements. While Chart.js uses 2D canvas and requires a single DOM node. 

In our specific case, both Rechart and Chart.js will do the work, but to ensure scalabilty ( keep good performances when we have lot of data / graphs) I recommend going with `Chart.js`. I've excluded` D3.js `as the graphes offered by the other tools are already enough, so it's not worth spending time learning it.

**Comment by swapnilraj** [comment]
Chart.js looks good, being canvas based is good.
Things that I really care about are the library is responsive and easy to use in React
Chart.js looks like it checks both the marks, happy to switch to it
