### ISSUE TITLE
Wrap all service calls with `try/catch`

### ISSUE THREAD

**Issue by vincenthongzy** [NethermindEth/restaking-dashboard#127]
> To display error messages and hide loading indicators, we must wrap server calls with `try/catch/finally` everywhere. It's better to do this in a separate PR. What do you think?

_Originally posted by @rubo in https://github.com/NethermindEth/restaking-dashboard/pull/118#discussion_r1679212794_

- [x] Home
- [x] AVS list
- [x] AVS details (https://github.com/NethermindEth/restaking-dashboard/pull/170)
- [x] Operator list
- [x] Operator details
- [x] LRT (done in #129)
- [x] LST

**Comment by rubo** [comment]
@Zishan-7 @vincenthongzy I think the list above is accurate, isn't it?

**Comment by vincenthongzy** [comment]
yes I am still missing AVS details
