### ISSUE TITLE
fix: ui issues and enhancements

### ISSUE THREAD

**Issue by kushagrasarathe** [NethermindEth/restaking-dashboard#88]
These UI issues and enhancements needs to be implemented: 

- Sidebar also scrolls-down along with the page content, hiding the sidebar title. Ideally sidebar should be fixed wrt to page content, keeping all links and title visible on screen without scrolling.

<img width="613" alt="Screenshot 2024-05-20 at 10 13 04 AM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/4a84e713-9bde-4449-89ec-886747f52838">

<hr/>

- Padding between tabs sections on smaller screens
<img width="244" alt="Screenshot 2024-05-20 at 11 08 35 AM" src="https://github.com/NethermindEth/restaking-dashboard/assets/76868364/b710eac3-903c-4cae-adf5-a62cef9b99d1">

<hr/>

- Fix mobile responsiveness for overflowing content 

<hr/>

- Close ham menu on smaller screens on navigating to a different path

**Comment by Abhii5496** [comment]
hey , can i work on this ?

**Comment by kushagrasarathe** [comment]
> hey , can i work on this ?

Hey @Abhii5496 I appreciate your willingness to contribute. I am currently working on this issue myself and it's in progress.

Thanks, 
Kushagra

**Comment by David-Mastalski** [comment]
So, instead of one button.js component that performs various events, you would like to create several buttons where each button will be responsible for something different? I can take care of it if you want
